export interface InformacionInt {
    REGIMEN_LABORAL:string,
    ZONA:string,
    ANIO: number,
    CONTRATO: string,
    ROL: string,
    CEDULA: string,
    ABREVIATURA:string,
    NOMBRE_EMPLEADO: string,
    ESTRUCTURA: string,
    CARGO: string,
    NUM_ESCALA: number,
    RMU: string,    
    FECHA_INGRESO: string,
    FECHA_SALIDA: string,
    FECHA_PAGO_ANT: string,
    UBICACION_INTERNA: string,
    TELF_TRABAJO: string,
    EXT_TRABAJO: number,
    EMAIL:  string,
    LUGAR_NACIMIENTO: string,

    FECHA_NACIMIENTO: string,
    LUGAR_DOMICILIO: string,
    DIR_DOMICILIO: string,
    TELEFONO_FIJO:  string,
    TELEFONO_MOVIL:  string,
    CEDULA_MILITAR: string,
    EMERGENCIA: string,
    NUM_AFIL_IESS: string,
    NUM_HSTR_CLINIC: string,
    TIPO_SANGRE: string,
    GENERO: string,
    ETNIA: string,
    DISCAPACIDAD:string,
    PORCENTAJE: string ,
    ESTADO_CIVIL: string,
    NOMBRE_CONYUGUE: string,
    NOMBRE_PADRE: string,
    NOMBRE_MADRE: string,
    BANCO: string,
    TIPO_CUENTA:string,
    NUM_CUENTA: string,

        DEPARTAMENTO: string,
        DMGES_TIPO: number,
        DIRECCION_TRABAJO: string,
        DMGES_CODIGO: string,
        DDMHC_CODIGO: string,
        DRLAB_CODIGO: string,
        DMPER_CODIGO: string,
        DEPENDENCIA: string,
        FEC_MAX: string,
}
